# Generated by Django 5.0.6 on 2024-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0002_alter_categorydb_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='Product_Image')),
            ],
        ),
    ]
