# Generated by Django 5.0.6 on 2024-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0003_productdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Pages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdb',
            name='Publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
