# Generated by Django 5.0.6 on 2024-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0005_alter_productdb_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='ISBN',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
