# Generated by Django 5.0.6 on 2024-06-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0006_alter_productdb_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='ISBN',
        ),
    ]
