# Generated by Django 5.0.6 on 2024-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0008_productdb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='status',
            field=models.CharField(default='pending', max_length=7),
        ),
    ]
