# Generated by Django 5.0.6 on 2024-08-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibApp', '0009_alter_productdb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
