# Generated by Django 5.0.6 on 2024-06-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('pages', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='approve', max_length=7)),
            ],
        ),
    ]
