# Generated by Django 5.0.6 on 2024-06-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='ProductName',
        ),
    ]
