# Generated by Django 5.0.6 on 2024-06-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_rename_product_name_product_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='language',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='pages',
            new_name='Pages',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='publication_date',
            new_name='Publication_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='publisher',
            new_name='Publisher',
        ),
    ]
