# Generated by Django 5.0.6 on 2024-06-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_rename_author_product_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='Product_image',
        ),
    ]
