# Generated by Django 5.0.6 on 2024-06-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_rename_description_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image',
            new_name='ProductImage',
        ),
    ]
