# Generated by Django 5.0.6 on 2024-07-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='approve', max_length=7),
        ),
    ]
