# Generated by Django 5.0.6 on 2024-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
