# Generated by Django 5.0.6 on 2024-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_register_db_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_db',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
