# Generated by Django 5.0.6 on 2024-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_remove_register_db_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_db',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
            preserve_default=False,
        ),
    ]
