# Generated by Django 5.0.6 on 2024-08-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_remove_register_db_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.register_db')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
