# Generated by Django 5.0.6 on 2024-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
