# Generated by Django 5.0.6 on 2024-08-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_alter_wishlist_unique_together_wishlist_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='cartdb',
            name='WishList',
            field=models.BooleanField(default=False),
        ),
    ]
