# Generated by Django 5.0.6 on 2024-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0020_delete_wishlist_cartdb_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
