# Generated by Django 5.0.6 on 2024-08-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_wishllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishllist',
            name='Product_Image',
            field=models.ImageField(default='exit', upload_to='product_images_Wish/'),
            preserve_default=False,
        ),
    ]
