# Generated by Django 5.0.6 on 2024-08-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_wishllist_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishllist',
            old_name='Product_Image',
            new_name='ProductImage',
        ),
    ]
