# Generated by Django 5.0.6 on 2024-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0023_rename_product_image_wishllist_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishllist',
            name='ProductImage',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
