# Generated by Django 5.0.6 on 2024-08-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0032_review_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishllist',
            old_name='Price',
            new_name='Product_Id',
        ),
        migrations.RemoveField(
            model_name='wishllist',
            name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='wishllist',
            name='ProductName',
        ),
    ]
