# Generated by Django 5.0.6 on 2024-08-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0035_remove_cartdb_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_db',
            old_name='Name',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='review_db',
            old_name='Review',
            new_name='Username',
        ),
        migrations.AddField(
            model_name='review_db',
            name='Product_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
