# Generated by Django 5.0.6 on 2024-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0037_review_db_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Product_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
