# Generated by Django 5.0.6 on 2024-08-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0045_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
